name: ShellCheck

on:
  push:

jobs:
  shellcheck:
    name: Run ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './linux-admin-toolkit/scripts'
